flowchart TD
%% generated in 0.01s
    examples__check_examples["examples.check-examples<br/>4 funcs"]
    nxdo__metrics["nxdo.metrics<br/>18 funcs"]
    scripts__check_import_layers["scripts.check_import_layers<br/>4 funcs"]
    src__nxdo["src.nxdo<br/>121 funcs"]
    src__nxdo ==>|6| examples__check_examples
    scripts__check_import_layers -->|3| examples__check_examples
    src__nxdo -->|2| nxdo__metrics
