"""Ticket generation integration with planfile."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from rich.console import Console

from nxdo.models import TaskPlan

console = Console()

TODO_MANAGED_START = "<!-- nxdo:generated-tasks:start -->"
TODO_MANAGED_END = "<!-- nxdo:generated-tasks:end -->"


def task_plan_to_tickets(task_plan: TaskPlan) -> list[dict[str, Any]]:
    """Convert TaskPlan to planfile ticket format.

    Args:
        task_plan: TaskPlan from nxdo planner

    Returns:
        List of ticket dictionaries in planfile format
    """
    tickets: list[dict[str, Any]] = []

    for task in task_plan.tasks:
        ticket = {
            "id": f"task-{task.number}",
            "title": task.title,
            "name": task.title,
            "description": task.description,
            "status": "pending",
            "priority": _map_priority(task.priority.value),
            "task_type": task.task_type.value,
            "estimated_hours": task.estimated_hours,
            "acceptance_criteria": task.acceptance_criteria,
            "dependencies": [f"task-{dep}" for dep in task.dependencies],
        }
        tickets.append(ticket)

    return tickets


def _map_priority(priority: str) -> str:
    """Map nxdo Priority to planfile priority."""
    priority_map = {
        "high": "critical",
        "medium": "high",
        "low": "medium",
    }
    return priority_map.get(priority.lower(), "medium")


def sync_to_todo_md(task_plan: TaskPlan, project_path: Path = Path(".")) -> dict[str, Any]:
    """Sync TaskPlan tasks to TODO.md as checkboxes.

    Writes a managed 'Generated by nxdo' section to todo.md (or TODO.md) with
    each task as a markdown checkbox. Manual content outside generated sections
    is preserved, and repeated runs replace the previous generated block.

    Args:
        task_plan: TaskPlan from nxdo planner
        project_path: Project root path

    Returns:
        Sync report dictionary with count of written tasks
    """
    todo_path = _resolve_todo_path(project_path)
    lines = _build_todo_section(task_plan)
    _sync_todo_section(todo_path, lines)
    return {"enabled": True, "todo_path": str(todo_path), "updated": len(task_plan.tasks)}


def _resolve_todo_path(project_path: Path) -> Path:
    """Return the TODO.md path, preferring existing file (case-insensitive)."""
    for name in ("TODO.md", "todo.md", "Todo.md"):
        candidate = project_path / name
        if candidate.exists():
            return candidate
    return project_path / "TODO.md"


def _build_todo_section(task_plan: TaskPlan) -> list[str]:
    """Build markdown lines for the generated task section."""
    _PRIORITY_EMOJI = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "⚪"}
    lines = [
        "",
        TODO_MANAGED_START,
        f"## Generated by nxdo — {task_plan.generated_at or 'latest'}",
        "",
    ]
    for task in task_plan.tasks:
        prio = _map_priority(task.priority.value)
        emoji = _PRIORITY_EMOJI.get(prio, "⚪")
        lines.append(f"- [ ] {emoji} {task.title}  <!-- nxdo:task-{task.number} -->")
        if task.description:
            lines.append(f"  {task.description}")
    lines.extend(["", TODO_MANAGED_END, ""])
    return lines


def _sync_todo_section(todo_path: Path, lines: list[str]) -> None:
    """Replace nxdo-managed TODO content, creating the file if needed."""
    existing = todo_path.read_text(encoding="utf-8") if todo_path.exists() else "# TODO\n"
    cleaned = _remove_generated_todo_sections(existing)
    todo_path.write_text(cleaned.rstrip("\n") + "\n" + "\n".join(lines), encoding="utf-8")


def _remove_generated_todo_sections(content: str) -> str:
    """Remove current managed blocks and legacy generated nxdo sections."""
    without_managed = _remove_managed_todo_blocks(content.splitlines())
    without_legacy = _remove_legacy_generated_todo_sections(without_managed)
    return "\n".join(without_legacy).rstrip("\n") + "\n"


def _remove_managed_todo_blocks(lines: list[str]) -> list[str]:
    """Remove sections bounded by nxdo managed block markers."""
    cleaned: list[str] = []
    in_managed_block = False
    for line in lines:
        if line.strip() == TODO_MANAGED_START:
            in_managed_block = True
            continue
        if in_managed_block:
            if line.strip() == TODO_MANAGED_END:
                in_managed_block = False
            continue
        cleaned.append(line)
    return cleaned


def _remove_legacy_generated_todo_sections(lines: list[str]) -> list[str]:
    """Remove old unbounded 'Generated by nxdo' sections."""
    cleaned: list[str] = []
    skipping_legacy_section = False

    for line in lines:
        is_nxdo_heading = line.startswith("## Generated by nxdo")
        is_next_heading = line.startswith("## ") and not is_nxdo_heading

        if is_nxdo_heading:
            skipping_legacy_section = True
            continue
        if skipping_legacy_section:
            if is_next_heading:
                skipping_legacy_section = False
                cleaned.append(line)
            continue
        cleaned.append(line)

    return cleaned


def _ensure_planfile_installed() -> bool:
    """Ensure planfile package is installed, auto-install if missing."""
    try:
        import planfile  # noqa: F401
        return True
    except ImportError:
        console.print("[yellow]⚠️  planfile not installed, attempting auto-install...[/yellow]")
        import subprocess
        import sys
        try:
            subprocess.run(
                [sys.executable, "-m", "pip", "install", "planfile", "-q"],
                check=True,
                capture_output=True,
            )
            # Retry import
            import importlib
            importlib.invalidate_caches()
            import planfile  # noqa: F401
            console.print("[green]✓[/green] planfile installed successfully")
            return True
        except Exception as install_exc:
            console.print(f"[red]✗[/red] Failed to install planfile: {install_exc}")
            return False


def sync_to_planfile(task_plan: TaskPlan, project_path: Path = Path(".")) -> dict[str, Any]:
    """Store TaskPlan tasks as planfile tickets in .planfile/ and sync to markdown.

    Uses planfile's Store API to persist tickets in .planfile/sprints/current.yaml,
    then calls planfile sync markdown to update TODO.md / CHANGELOG.md.
    Auto-installs planfile package if not available.

    Args:
        task_plan: TaskPlan from nxdo planner
        project_path: Project root path

    Returns:
        Report dict with created count and planfile directory path
    """
    if not _ensure_planfile_installed():
        return {"enabled": False, "created": 0, "planfile_dir": ""}

    try:
        from planfile.core.store import Store
        from planfile.core.models import Ticket, TicketStatus
        from planfile.cli.groups.sync.core import sync_integration
    except ImportError as exc:
        console.print(f"[yellow]⚠️  planfile import failed after install: {exc}[/yellow]")
        return {"enabled": False, "created": 0, "planfile_dir": ""}

    store = Store(project_path)
    created = 0

    for task in task_plan.tasks:
        ticket_id = f"LANE-{task.number}"
        priority = _map_priority(task.priority.value)
        ticket = Ticket(
            id=ticket_id,
            name=task.title,
            description=task.description or "",
            status=TicketStatus.open,
            priority=priority,
            sprint="current",
            acceptance_criteria=task.acceptance_criteria or [],
        )
        try:
            store.create_ticket(ticket)
            created += 1
        except Exception:
            pass

    try:
        sync_integration("markdown", str(project_path), dry_run=False, direction="to", show_header=False)
    except Exception as exc:
        console.print(f"[yellow]⚠️  markdown sync warning: {exc}[/yellow]")

    planfile_dir = str(store.base_dir)
    console.print(f"[green]✓[/green] Stored {created} tickets in {planfile_dir}")
    return {"enabled": True, "created": created, "planfile_dir": planfile_dir}


def export_to_planfile_yaml(task_plan: TaskPlan, output_path: Path) -> None:
    """Export TaskPlan to planfile YAML format.

    Args:
        task_plan: TaskPlan from nxdo planner
        output_path: Path to write planfile YAML
    """
    import yaml

    strategy_data = {
        "name": task_plan.project_name,
        "description": task_plan.summary,
        "project_type": "software",
        "domain": "development",
        "goal": task_plan.summary,
        "sprints": [
            {
                "id": 1,
                "name": "Sprint 1",
                "goal": task_plan.summary,
                "task_patterns": [
                    {
                        "id": f"task-{task.number}",
                        "title": task.title,
                        "description": task.description,
                        "status": "pending",
                        "priority": _map_priority(task.priority.value),
                        "task_type": task.task_type.value,
                        "estimated_hours": task.estimated_hours,
                        "acceptance_criteria": task.acceptance_criteria,
                        "dependencies": [f"task-{dep}" for dep in task.dependencies],
                    }
                    for task in task_plan.tasks
                ],
            }
        ],
    }

    with open(output_path, "w", encoding="utf-8") as f:
        yaml.dump(strategy_data, f, default_flow_style=False)

    console.print(f"[green]✓ Exported strategy to {output_path}[/green]")
